### ISSUE TITLE
Experiments on SVHN

### ISSUE THREAD

**Issue by jungtaekkim** [Felix-Petersen/diffsort#2]
Hi @Felix-Petersen,

Thank you for sharing a great project.

I would like to run the experiments on SVHN, but I encountered some errors.

First of all, I would like to ask if the input dimensionality, e.g., (batch size, channel size, height, width), is correct.

Unlike these experiments, MNIST is given like (batch size, n, channel size, height, width).

If such a shape is correct, please let me know how I can run the SVHN experiments.

Thank you again.

Best regards,
Jungtaek.

**Comment by Felix-Petersen** [comment]
Hi @jungtaekkim ,

Thanks for reaching out! I found the error, and it is fixed now. (I had forgotten to include the `collate_fn` in the code, which is responsible for extending the SVHN data loader.)
The reason for the asserted 4 dimensions in the model was that the convolution model does not work with two batch dimensions, I adjusted the model to make it more flexible.

Please tell me if you still encounter some issues.

Best regards,

Felix
