### ISSUE TITLE
Is it possible to use diffsort to rank, keeping differentiability?

### ISSUE THREAD

**Issue by davips** [Felix-Petersen/diffsort#5]
Related: Do you know any work/implementation about soft indexing similar to numpy/scipy `argsort` and `partition`?

**Comment by Felix-Petersen** [comment]
Yes, `diffsort` is actually a diffargsort or more concretely the module returns a tuple of `sorted_vectors, permutation_matrices` where `sorted_vectors` is the output of the sorting operation and `permutation_matrices` is the soft version of argsort / rank.

**Comment by arunkumar-singh** [comment]
Hi

How to use the DiffsortNet for a batch of input vectors of size bxN, where b is the batch size and N is the vector-length?

**Comment by arunkumar-singh** [comment]
> Hi
> 
> How to use the DiffsortNet for a batch of input vectors of size bxN, where b is the batch size and N is the vector-length?

Never mind, I got it
